OpenHubAPI/OpenHubAPI/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include
from rest_framework import routers
from django.urls import path
from data.views.views import HardwareViewSet, AccessoryViewSet, ChannelViewSet, HubViewSet, \
    IOViewSet
#
# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'accessories', AccessoryViewSet)
# router.register(r'hardwares', HardwareViewSet)
# router.register(r'channel', ChannelViewSet)
# router.register(r'calibration', CalibrationViewSet)
# router.register(r'hubs', HubViewSet)
# router.register(r'io', IOViewSet)


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include('data.urls')),
    ]

OpenHubAPI/data/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include
from django.views.decorators.csrf import csrf_exempt
from rest_framework import routers
from django.urls import path
from data.views.views import HardwareViewSet, AccessoryViewSet, ChannelViewSet, HubViewSet, \
    IOViewSet, createUser,listHubAccessories,listHubHardware,listHubChannels,ChannelStatsViewSet,ChannelStatDataPointViewSet
from django.contrib.auth.views import LoginView


# Routers provide an easy way of automatically determining the URL conf.
router = routers.SimpleRouter()
router.register(r'accessories', AccessoryViewSet)
router.register(r'hardwares', HardwareViewSet)
router.register(r'channel', ChannelViewSet)
router.register(r'channelstats', ChannelStatsViewSet, basename='channelstats')
router.register(r'channelstatdatapoint', ChannelStatDataPointViewSet, basename='channelstatdatapoint')
router.register(r'hubs', HubViewSet, basename='hubs')
router.register(r'io', IOViewSet)

from data.views.views import index
from data.views.views import video_streams, logout

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    url(r'^login/$', LoginView.as_view(template_name="registration/login.html"), name="login"),
    url(r'^logout/$', logout, name="logout"),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # path('start', views.start, name='start'),
    # path('index', index, name='index'),
    url(r'^admin/', admin.site.urls),
    path('post/ajax/hardware', HardwareViewSet.postHardware, name="post_hardware"),
    path('post/ajax/hardware/form_type/', HardwareViewSet.getHardwareTypeForm,
         name="get_hardware_types"),
    path('post/ajax/hardware/form_io/', HardwareViewSet.getHardwareIoForm,
         name="get_hardware_io"),
    path('post/ajax/accessory', AccessoryViewSet.postAccessory, name="post_accessory"),
    path('delete/ajax/accessory', AccessoryViewSet.deleteAccessory, name="delete_accessory"),
    path('patch/ajax/accessory', AccessoryViewSet.updateAccessory, name="update_accessory"),
    path('delete/ajax/hub', HubViewSet.deleteHub, name="delete_hub"),
    path('patch/ajax/hub', HubViewSet.updateHub, name="update_hub"),

    path('delete/ajax/channel', ChannelViewSet.deleteChannel, name="delete_channel"),
    path('delete/ajax/hardware', HardwareViewSet.deleteHardware, name="delete_hardware"),
    path('delete/ajax/io', IOViewSet.deleteIO, name="delete_io"),

    path('post/ajax/hardware/io/', HardwareViewSet.postHardwareIO,
         name="post_hardware_io"),
    path('post/ajax/channel', HardwareViewSet.postChannel, name="post_channel"),
    path('patch/ajax/channel', ChannelViewSet.updateChannel, name="update_channel"),
    path('post/ajax/config', HardwareViewSet.postConfig, name="post_config"),
    path('patch/ajax/hardware', HardwareViewSet.updateHardware, name="update_hardware"),
    path('hardwares/<uuid:hardware_id>/config', HardwareViewSet.getConfig),
    path('hardwares/<uuid:hardware_id>/channels', HardwareViewSet.getChannels),
    path('channels/<uuid:channel_id>/io', ChannelViewSet.listIO),
    path('accessories/<uuid:accessory_id>/data_transformer', AccessoryViewSet.postDataTransformer),

    path('post/ajax/hub', HubViewSet.postHub, name="post_hub"),
    path('hub/', csrf_exempt(HubViewSet.postHub)),
    path('pipico/', csrf_exempt(HardwareViewSet.postHardware)),

    path('hubs/<uuid:hub_id>/hardwares', view=listHubHardware),
    path('hubs/<uuid:hub_id>/channels', view=listHubChannels),
    path('hubs/<uuid:hub_id>/accessories', view=listHubAccessories),
    path('openhubapi/about', HubViewSet.about),
    path('streams/', video_streams, name="video_streams"),
    path('createuser/', createUser, name="create_user"),
    url(r'^$',LoginView.as_view(template_name="registration/login.html"),name='index'),

]

OpenHubAPI/data/models/models.py
import mptt
from django.db import models
import uuid
from django.utils import timezone
import time
from polymorphic.models import PolymorphicModel
from mptt.models import MPTTModel, TreeForeignKey
from django.contrib.auth.models import User

class Hub(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True, blank=True)
    ip = models.URLField()
    category = models.CharField(max_length=255, null=True)
    type = models.CharField(max_length=255, null=True)
    display_name = models.CharField(max_length=255, null=True)
    aid = models.IntegerField()

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super().save(*args, **kwargs)

    class Meta:
        indexes = [
            models.Index(fields=['id']),
        ]


class Hardware(PolymorphicModel):
    class Type(models.TextChoices):
        DHT22 = 'DHT22'
        MCP3008 = 'MCP3008'
        ModProbe = 'ModProbe'
        PiPico = 'PiPico'
        Pi = 'Pi'
        VEML7700 = 'VEML7700'
        AdafruitStepperMotorHAT = 'AdafruitStepperMotorHAT'
        PMSA0031 = 'PMSA0031'
        AM2315 = 'AM2315'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True, blank=True)

    type = models.CharField(
        max_length=30,
        choices=Type.choices,
        default=Type.PiPico,
    )

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    hub = models.ForeignKey(Hub, on_delete=models.CASCADE, null=False)

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()

        return super().save(*args, **kwargs)

    class Meta:
        indexes = [
            models.Index(fields=['id']),
        ]

class Pi(Hardware):
    def __init__(self,*args, **kwargs):
        super(Hardware,self).__init__(*args, **kwargs)

class PiPico(Hardware):
    serial_com = models.CharField(max_length=100, null=True)
    pi_gpio_interrupt = models.IntegerField()


class DHT22(Hardware):
    pin = models.IntegerField()


class MCP3008(Hardware):
    sck = models.IntegerField()
    miso = models.IntegerField()
    cs_pin = models.IntegerField()
    num_channels = models.IntegerField()


class ModProbe(Hardware):
    base_dir = models.CharField(max_length=100, null=True)
    file_name = models.CharField(max_length=100, null=True)


class VEML7700(Hardware):
    scl = models.IntegerField()
    sda = models.IntegerField()

class AdafruitStepperMotorHAT(Hardware):
    scl = models.IntegerField()
    sda = models.IntegerField()

class PMSA0031(Hardware):
    scl = models.IntegerField()
    sda = models.IntegerField()
    reset = models.IntegerField()

class AM2315(Hardware):
    scl = models.IntegerField()
    sda = models.IntegerField()

class HardwareChannelTypes(models.Model):
    hardware_type = models.CharField(
        max_length=25
    )
    channel_type = models.CharField(
        max_length=25
    )


class Channel(models.Model):
    def __str__(self):
        return self.get_name_display()

    def get_name_display(self):
        name = ''
        if self.nickname is not None and self.nickname != '':
            name = self.nickname
        else:
            if self.hardware is not None:
                name = name + self.hardware.type + ' / '
                name = name + self.type + ' / ' + str(self.channel_index) + ' / ' + str(self.id)
        return name

    class Type(models.TextChoices):
        DHT22Humidity = 'DHT22Humidity'
        DHT22Temp = 'DHT22Temp'
        MCP3008Analog = 'MCP3008Analog'
        ModProbeTemp = 'ModProbeTemp'
        PiPicoACAnalog = 'PiPicoACAnalog'
        PiPicoAnalog = 'PiPicoAnalog'
        PiPicoPump = 'PiPicoPump'
        PiPicoRelay = 'PiPicoRelay'
        AdafruitStepperMotor = 'AdafruitStepperMotor'
        VEML7700Light = 'VEML7700Light'
        VEML7700Lux = 'VEML7700Lux'
        PiRelay = 'PiRelay'
        AM2315Humidity = 'AM2315Humidity'
        AM2315Temperature = 'AM2315Temperature'
        PMSA003125 = 'PMSA003125'
        PMSA0031100 = 'PMSA0031100'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True, blank=True)
    channel_index = models.IntegerField(null=True)
    type = models.CharField(
        max_length=25
    )
    nickname = models.CharField(
        max_length=100,
        default=None,
        blank=True,
        null=True
    )
    hardware = models.ForeignKey(Hardware, on_delete=models.CASCADE, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    hub = models.ForeignKey(Hub, on_delete=models.CASCADE, null=False)
    keep_statistics = models.BooleanField(null=True, blank=True, default=False)

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()

        return super().save(*args, **kwargs)

    class Meta:
        indexes = [
            models.Index(fields=['id', 'hardware']),
        ]


class HardwareIO(PolymorphicModel):
    SPI = 'SPI'
    Serial = 'Serial'
    PWM = 'PWM'
    I2C = 'I2C'
    DeviceFile = 'Device File'
    MCPChannel = 'MCP Channel'
    PiPicoACAnalog = 'Pi Pico AC Analog'
    PiPicoAnalog = 'Pi Pico Analog'
    PiGPIO = 'Pi GPIO'
    StepperMotor = 'Stepper Motor'
    hardware_io_types_choices = [(SPI, SPI), (Serial, Serial), (PWM, PWM), (I2C, I2C), (DeviceFile, DeviceFile),
                                 (MCPChannel, MCPChannel), (PiPicoAnalog, PiPicoAnalog),
                                 (PiPicoACAnalog, PiPicoACAnalog), (PiGPIO, PiGPIO),(StepperMotor,StepperMotor)]

    label = models.CharField(max_length=255, null=True)

    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True, blank=True)

    parent_hardware = models.ForeignKey(Hardware, on_delete=models.CASCADE, blank=True, null=True,
                                        related_name="%(app_label)s_%(class)s_related",
                                        related_query_name="%(app_label)s_%(class)ss")
    child_hardware = models.ForeignKey(Hardware, on_delete=models.CASCADE, blank=True, null=True)
    child_channel = models.ForeignKey(Channel, on_delete=models.CASCADE, blank=True, null=True)
    type = models.CharField(max_length=25, choices=hardware_io_types_choices, default=PiPicoAnalog)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    hub = models.ForeignKey(Hub, on_delete=models.CASCADE, null=False)

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()

        return super().save(*args, **kwargs)

    class Meta:
        indexes = [
            models.Index(fields=['id', 'parent_hardware', 'child_channel']),
        ]


class PiPins(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    hardware_io = models.ForeignKey(HardwareIO, on_delete=models.CASCADE, blank=True, null=True)
    pin = models.IntegerField()

    class Meta:
        indexes = [
            models.Index(fields=['hardware_io']),
        ]


class SPIIo(HardwareIO):
    sck = models.IntegerField()
    miso = models.IntegerField()
    mosi = models.IntegerField()


class SerialIo(HardwareIO):
    port = models.CharField(max_length=100)


class PwmIo(HardwareIO):
    en = models.IntegerField()
    duty_max = models.IntegerField()
    duty_min = models.IntegerField()
    freq = models.IntegerField()


class I2cIo(HardwareIO):
    scl = models.IntegerField()
    sda = models.IntegerField()


class DeviceFileIo(HardwareIO):
    base_dir = models.CharField(max_length=100, null=True)
    device_file = models.CharField(max_length=100, null=True)


class MCPAnalogIo(HardwareIO):
    channel_index = models.IntegerField()


class PiPicoAnalogIo(HardwareIO):
    pin = models.IntegerField()


class PiPicoACAnalogIo(HardwareIO):
    pin = models.IntegerField()


class PiGpio(HardwareIO):
    pin = models.IntegerField()

class StepperMotor(HardwareIO):
    full_rotation_steps = models.IntegerField()
    number_of_rotations = models.FloatField()
    step_pause_time = models.FloatField()


class Accessory(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True, blank=True)

    hub = models.ForeignKey(Hub, on_delete=models.CASCADE, null=False)

    category = models.CharField(max_length=255, null=True)
    type = models.CharField(max_length=255, null=True)
    display_name = models.CharField(max_length=255, null=True)
    aid = models.IntegerField()
    channels = models.ManyToManyField(Channel)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super().save(*args, **kwargs)

    @property
    def has_data_transformer(self):
        return self.datatransformer_set.count() > 0

    @property
    def datatransformer(self):
        try:
            return self.datatransformer_set.first().get_root()
        except:
            print('datatransformer error sorta')

OpenHubAPI/data/views.py
from django.shortcuts import render

# Create your views here.

from django.http import JsonResponse
from django.core import serializers
from .forms.forms import CalibrationForm
from .models.models import Calibration


def index(request):
    context = {'title': 'HomeHub'}
    return render(request, 'home.html', context)
#
#
# def postFriend(request):
#     # request should be ajax and method should be POST.
#     if request.is_ajax and request.method == "POST":
#         # get the form data
#         form = FriendForm(request.POST)
#         # save the data and after fetch the object in instance
#         if form.is_valid():
#             instance = form.save()
#             # serialize in new friend object in json
#             ser_instance = serializers.serialize('json', [instance, ])
#             # send to client side.
#             return JsonResponse({"instance": ser_instance}, status=200)
#         else:
#             # some form errors occured.
#             return JsonResponse({"error": form.errors}, status=400)
#
#     # some error occured
#     return JsonResponse({"error": ""}, status=400)
#
#
# # chat/views.py
# from django.shortcuts import render
#
#
# def start(request):
#     return render(request, 'start.html', {})
#
#
# def calibrate(request, room_name):
#     return render(request, 'calibrate.html', {
#         'room_name': room_name
#     })

OpenHubAPI/data/templates/accessories.html
{% extends './base_site.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
    <h1>{{ title }}</h1>
    <h1>Accessories</h1>
    <div class="container-fluid">
        <form id="accessory-form">
            <div class="row">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group col-4">
                        <label class="col-12">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                {% for field in form.hidden_fields %}
                    {{ field }}
                {% endfor %}
            </div>
            <div class="row">
                <div class="form-group col-4">

                    <input type="submit" class="btn btn-primary" value="Create accessory"/>
                </div>
            </div>
        </form>
    </div>
    <hr/>
    <div class="container-fluid">
        <table class="table table-striped table-sm " id="my_accessorys" style="width:100%">
            <thead>
            <tr>
                <th>Serial No.</th>
                <th>Category</th>
                <th>Type</th>
                <th>Display Name</th>
                <th>AID</th>
                <th>Updated At</th>
                <th>Created At</th>
            </tr>
            </thead>
            <tbody>
            {% for accessory in accessories %}
                <tr>
                    <td><a href=/accessories/{{ accessory.id }} style="color:#0000EE">{{ accessory.id }}</a></td>
                    <td>{{ accessory.category }}</td>
                    <td>{{ accessory.type }}</td>
                    <td>{{ accessory.display_name }}</td>
                    <td>{{ accessory.aid }}</td>
                    <td>{{ accessory.updated_at }}</td>
                    <td>{{ accessory.created_at }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock content %}
{% block javascript %}
    {{ block.super }}
    <script>
        /*
            On submiting the form, send the POST ajax
            request to server and after successfull submission
            display the object.
        */
        $("#accessory-form").submit(function (e) {
            // preventing from page reload and default actions
            e.preventDefault();
            // serialize the data for sending the form data.
            var serializedData = $(this).serialize();
            // make POST ajax call
            $.ajax({
                type: 'POST',
                url: "{% url 'post_accessory' %}",
                data: serializedData,
                success: function (response) {
                    // on successfull creating object
                    // 1. clear the form.
                    $("#accessory-form").trigger('reset');
                    // 2. focus to nickname input
                    $("#id_id").focus();

                    // display the newly accessory to table.
                    var instance = JSON.parse(response["instance"]);
                    var fields = instance[0]["fields"];
                    var pk = instance[0]["pk"];
                    var link = /accessories/ + pk
                    $("#my_accessorys tbody").prepend(
                        `<tr>
                    <td><a href=${link} style="color:#0000EE">${pk}</a></td>
                    <td>${fields["category"] || ""}</td>
                    <td>${fields["type"] || ""}</td>
                    <td>${fields["display_name"] || ""}</td>
                    <td>${fields["aid"] || ""}</td>
                    <td>${fields["updated_at"] || ""}</td>
                    <td>${fields["created_at"] || ""}</td>
                    <td>${fields || ""}</td>

                    </tr>`
                    )
                },
                error: function (response) {
                    // alert the error if any error occured
                    alert(response["responseJSON"]["error"]);
                }
            })
        })
    </script>
{% endblock javascript %}

OpenHubAPI/data/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

OpenHubAPI/data/templates/channel_stats.html
<!DOCTYPE html>
<html lang="en">


<div class="container-fluid">
    <table class="table table-striped table-sm" id="stats">
        <thead>
        <tr>
            <th>Serial No.</th>
            <th>Type</th>
            <th>Value</th>
            <th>Created At</th>
            <th>Updated At</th>
        </tr>
        </thead>
        <tbody>
        {% for stat in channel_stats %}
            <tr>
                <td>{{ stat.id }}</td>
                <td>{{ stat.type }}</td>
                <td>{{ stat.value }}</td>
                <td>{{ stat.created_at }}</td>
                <td>{{ stat.updated_at }}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
</html>

OpenHubAPI/data/templates/channel_stats_graph.html
<!DOCTYPE html>
<html lang="en">


<div class="container-fluid">
    <table class="table table-striped table-sm" id="stats">
        <thead>
        <tr>
            <th>Serial No.</th>
            <th>Type</th>
            <th>Value</th>
            <th>Created At</th>
            <th>Updated At</th>
        </tr>
        </thead>
        <tbody>
        {% for stat in channel_stats %}
            <tr>
                <td>{{ stat.id }}</td>
                <td>{{ stat.type }}</td>
                <td>{{ stat.value }}</td>
                <td>{{ stat.created_at }}</td>
                <td>{{ stat.updated_at }}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
</html>

OpenHubAPI/data/templates/hardwares.html
{% extends './base_site.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
    <h1>{{ title }}</h1>
    <h1>Create Hardware:</h1>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md">
                <form id="hardware-type-selection-form">
                    <div class="row">
                        {% csrf_token %}
                        {% for field in type_form.visible_fields %}
                            <div class="form-group col-4">
                                <label class="col-12">{{ field.label }}</label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        {#                        <input type="submit" class="btn btn-primary" value="Select Hardware Type"/>#}
                    </div>
                </form>


            </div>
        </div>

        <form id="hardware-form">
            <div class="row">
                {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="form-group col-4">
                        <label class="col-12">{{ field.label }}</label>
                        {{ field }}
                    </div>

                {% endfor %}
                {% for field in form.hidden_fields %}
                    {{ field }}

                {% endfor %}

            </div>
            <div class="row">
                <div class="form-group col-4">

                    <p><input type="submit" class="btn btn-primary" value="Create hardware"/></p>
                </div>
            </div>
        </form>
    </div>
    <hr/>

    <div class="container-fluid">
        <table class="table table-striped table-sm" id="my_hardwares">
            <thead>
            <tr>
                <th>Serial No.</th>
                <th>Type</th>
                <th>Updated At</th>
                <th>Created At</th>
            </tr>
            </thead>
            <tbody>
            {% for hardware in hardwares %}
                <tr>
                    <td><a href=/hardwares/{{ hardware.id }} style="color:#0000EE">{{ hardware.id }}</a></td>
                    <td>{{ hardware.type }}</td>
                    <td>{{ hardware.updated_at }}</td>
                    <td>{{ hardware.created_at }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock content %}
{% block javascript %}
        {{ block.super }}

    <script>
        $("#hardware-type-selection-form").submit(function (e) {
            e.preventDefault();
            var data = $("#hardware-type-selection-form").serialize()
            $.ajax({
                url: "{% url 'get_hardware_types' %}",
                type: "POST",
                data: data,
                success: function (response) {

                    $("#hardware-form").trigger('reset');

                    $("#hardware-form").html('{% csrf_token %}'
                        + response + '<input type="submit" class="btn btn-primary" value="Create hardware"/>'
                    );

                    console.log(response);
                    // response is form in html format
                    {#$("#formdiv").html(response);#}
                }
            })
        })

        $("#id_type").on('change', function () {
            $("#hardware-type-selection-form").submit()
        })

        /*
            On submiting the form, send the POST ajax
            request to server and after successfull submission
            display the object.
        */
        $("#hardware-form").submit(function (e) {
            // preventing from page reload and default actions
            e.preventDefault();
            // serialize the data for sending the form data.
            var serializedData = $(this).serialize();
            // make POST ajax call
            $.ajax({
                type: 'POST',
                url: "{% url 'post_hardware' %}",
                data: serializedData,
                success: function (response) {
                    // on successfull creating object
                    // 1. clear the form.
                    $("#hardware-form").trigger('reset');
                    // 2. focus to nickname input
                    $("#id_id").focus();

                    // display the newly hardware to table.
                    var instance = JSON.parse(response["instance"]);
                    var fields = instance[0]["fields"];
                    var pk = instance[0]["pk"];
                    var link = /hardwares/ + pk
                    $("#my_hardwares tbody").prepend(
                        `<tr>
                    <td><a href=${link} style="color:#0000EE">${pk}</a></td>
                    <td>${fields["type"] || ""}</td>
                    <td>${fields["updated_at"] || ""}</td>
                    <td>${fields["created_at"] || ""}</td>
                    </tr>`
                    )
                },
                error: function (response) {
                    // alert the error if any error occured
                    alert(response["responseJSON"]["error"]);
                }
            })
        })
    </script>
{% endblock javascript %}

OpenHubAPI/data/templates/hubs.html
{% extends './base_site.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
    <h1>Hubs</h1>
    <div class="container-fluid">
        <form id="hub-form">
            <div class="row">
                {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="form-group col-4">
                        <label class="col-12">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}
                {% for field in form.hidden_fields %}
                    {{ field }}
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-md-1">
                    <input type="submit" class="btn btn-primary" value="Create Hub"/>
                </div>
            </div>

        </form>
    </div>
    <hr/>
    <div class="container-fluid">
        <table class="table table-striped table-sm " id="my_hubs" style="width:100%">
            <thead>
            <tr>
                <th>Serial No.</th>
                <th>Category</th>
                <th>Type</th>
                <th>Display Name</th>
                <th>AID</th>
                <th>Updated At</th>
                <th>Created At</th>
            </tr>
            </thead>
            <tbody>
            {% for hub in hubs %}
                <tr>
                    <td><a href=/hubs/{{ hub.id }} style="color:#0000EE">{{ hub.id }}</a></td>
                    <td>{{ hub.category }}</td>
                    <td>{{ hub.type }}</td>
                    <td>{{ hub.display_name }}</td>
                    <td>{{ hub.aid }}</td>
                    <td>{{ hub.updated_at }}</td>
                    <td>{{ hub.created_at }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock content %}
{% block javascript %}
    {{ block.super }}

    <script>
        /*
            On submiting the form, send the POST ajax
            request to server and after successfull submission
            display the object.
        */
        $("#hub-form").submit(function (e) {
            // preventing from page reload and default actions
            e.preventDefault();
            // serialize the data for sending the form data.
            var serializedData = $(this).serialize();
            // make POST ajax call
            $.ajax({
                type: 'POST',
                url: "{% url 'post_hub' %}",
                data: serializedData,
                success: function (response) {
                    // on successfull creating object
                    // 1. clear the form.
                    $("#hub-form").trigger('reset');
                    // 2. focus to nickname input
                    $("#id_id").focus();

                    // display the newly accessory to table.
                    var instance = JSON.parse(response["instance"]);
                    var fields = instance[0]["fields"];
                    var pk = instance[0]["pk"];
                    var link = /accessories/ + pk
                    $("#my_hubs tbody").prepend(
                        `<tr>
                    <td><a href=${link} style="color:#0000EE">${pk}</a></td>
                    <td>${fields["category"] || ""}</td>
                    <td>${fields["type"] || ""}</td>
                    <td>${fields["display_name"] || ""}</td>
                    <td>${fields["aid"] || ""}</td>
                    <td>${fields["updated_at"] || ""}</td>
                    <td>${fields["created_at"] || ""}</td>
                    <td>${fields || ""}</td>

                    </tr>`
                    )
                },
                error: function (response) {
                    // alert the error if any error occured
                    alert(response["responseJSON"]["error"]);
                }
            })
        })
    </script>
{% endblock javascript %}